### ISSUE TITLE
Error: Parsing audio-file option

### ISSUE THREAD

**Issue by Silipwn** [trizen/youtube-viewer#294] opened 2020-01-28 07:12 UTC
**Issue:**
Unable to play videos with mpv on Archlinux. 
**Versions:**
youtube-viewer: 3.7.0
mpv: 0.32.0
**Debug Output with --debug**
```
Searched for test and opened a random video
> Resolution: 1080
-> Video itag: 248
-> Audio itag: 251
-> Video type: video/webm; codecs="vp9"
-> Audio type: audio/webm; codecs="opus"
-> Command: /usr/bin/mpv --audio-file https\:\/\/r3\-\-\-sn\-h5576n7r\.googlevideo\.com\/videoplayback\?expire\=1580216609\&ei\=wdwvXsusNeuoz7sP9Ou16As\&ip\=X\.X\.X\.X\&id\=o\-ANlKjq\-jZT2UhuOEepHgrASSgkiH_rKa6mWebgX22D2T\&itag\=251\&source\=youtube\&requiressl\=yes\&mm\=31\%2C29\&mn\=sn\-h5576n7r\%2Csn\-h557snlz\&ms\=au\%2Crdu\&mv\=m\&mvi\=2\&pl\=24\&initcwndbps\=285000\&vprv\=1\&mime\=audio\%2Fwebm\&gir\=yes\&clen\=12853937\&dur\=781\.661\&lmt\=1541447419519037\&mt\=1580194910\&fvip\=3\&keepalive\=yes\&fexp\=23842630\&c\=WEB\&txp\=3511222\&sparams\=expire\%2Cei\%2Cip\%2Cid\%2Citag\%2Csource\%2Crequiressl\%2Cvprv\%2Cmime\%2Cgir\%2Cclen\%2Cdur\%2Clmt\&sig\=ALgxI2wwRAIgSDeKOwW7Ecx0P2Bue7UzQB_sRPJnSm9guFTs8m981u4CIACHksB\-FAJMfHajGiky1tmg23qCLAXoqcP1EIq1mlg2\&lsparams\=mm\%2Cmn\%2Cms\%2Cmv\%2Cmvi\%2Cpl\%2Cinitcwndbps\&lsig\=AHylml4wRQIgQn0EUSOTSAYG\-DLzLcoDXo2kVAqkY_yNsx8pxYk6rkECIQCzA3AlmINgyOhRgEtPJlJEMqmKnm_TJN_Glol2LjBDJg\%3D\%3D --really-quiet --title 27\ VIRAL\ HACKS\ TESTED\ AND\ BUSTED --no-ytdl https\:\/\/r3\-\-\-sn\-h5576n7r\.googlevideo\.com\/videoplayback\?expire\=1580216609\&ei\=wdwvXsusNeuoz7sP9Ou16As\&ip\=X\.X\.X\.X\&id\=o\-ANlKjq\-jZT2UhuOEepHgrASSgkiH_rKa6mWebgX22D2T\&itag\=248\&aitags\=133\%2C134\%2C135\%2C136\%2C137\%2C160\%2C242\%2C243\%2C244\%2C247\%2C248\%2C278\%2C394\%2C395\%2C396\%2C397\%2C398\&source\=youtube\&requiressl\=yes\&mm\=31\%2C29\&mn\=sn\-h5576n7r\%2Csn\-h557snlz\&ms\=au\%2Crdu\&mv\=m\&mvi\=2\&pl\=24\&initcwndbps\=285000\&vprv\=1\&mime\=video\%2Fwebm\&gir\=yes\&clen\=119388400\&dur\=781\.640\&lmt\=1541409831540578\&mt\=1580194910\&fvip\=3\&keepalive\=yes\&fexp\=23842630\&c\=WEB\&txp\=3535432\&sparams\=expire\%2Cei\%2Cip\%2Cid\%2Caitags\%2Csource\%2Crequiressl\%2Cvprv\%2Cmime\%2Cgir\%2Cclen\%2Cdur\%2Clmt\&sig\=ALgxI2wwRAIgPrkV7XaSCJd1y2Ym7O0o5MsO_YAIWv5oqIk5h\-8RgvUCIBtkdTHtZ6cTY__mmuvbS5UYYT5jvn0Iy21IbRnVS7_4\&lsparams\=mm\%2Cmn\%2Cms\%2Cmv\%2Cmvi\%2Cpl\%2Cinitcwndbps\&lsig\=AHylml4wRQIgQn0EUSOTSAYG\-DLzLcoDXo2kVAqkY_yNsx8pxYk6rkECIQCzA3AlmINgyOhRgEtPJlJEMqmKnm_TJN_Glol2LjBDJg\%3D\%3D
Error parsing commandline option audio-file: option requires parameter
```

**Comment by trizen** [comment] 2020-01-28 13:29
Duplicate of https://github.com/trizen/youtube-viewer/issues/290. Fixed in version 3.7.1

**Closed by trizen** 2020-01-28 13:29 UTC
