### ISSUE TITLE
Video > Play don't react

### ISSUE THREAD

**Issue by KimHono** [trizen/youtube-viewer#295] opened 2020-01-29 07:50 UTC
Hi !
Some friends have been using youtube-viewer for several months without issues, thanks a lot.
But since the last update, no video can be read anymore.

The Play function, in "Video" menu, don't react.
While in a terminal, there is only one error message:
"Error parsing commandline option audio-file: option requires parameter"

Version : GTK YouTube Viewer 3.7.0
OS : ArchLinux 5.4.15-arch1-1

**Comment by trizen** [comment] 2020-01-29 08:50
Duplicate of #290. Fixed in version 3.7.1. Wait for an update, or install `gtk-youtube-viewer-git` from AUR.

**Closed by trizen** 2020-01-29 08:50 UTC
