### ISSUE TITLE
No streaming URL has been found

### ISSUE THREAD

**Issue by madalincolea** [trizen/youtube-viewer#321] opened 2020-05-29 09:04 UTC
Great application. Have been using it for 2 years and is working great. 
Recently switched to Fedora 32 from Arch where all was working great. 

I am using the Fedora copr repo from the README and have checked to see if all deps are installed and correct versions (seems to be OK).

I get the following error when trying to play a specific URL 

`** GET https://www.youtube.com/get_video_info?video_id=JvGiWIreg-k&el=detailpage&ps=default&eurl=&gl=US&hl=en ==> 200 OK (1s)`
`:: Using player_response to extract the streaming URLs...`
`:: Found 5 streaming URLs...`
`[!] No streaming URL has been found...`

I cannot seem to get this particular video to play, although it worked perfectly last week on Arch (same URL, ofc.)

Any thoughts?

**Comment by trizen** [comment] 2020-05-29 09:28
Should be fixed in https://github.com/trizen/youtube-viewer/commit/b2ac969756ed1e7d3d81c9c4d4ec3a740deadc1f.

Can you confirm the fix? If so, a new release will be tagged soon.

**Comment by madalincolea** [comment] 2020-05-29 09:57
> Should be fixed in [b2ac969](https://github.com/trizen/youtube-viewer/commit/b2ac969756ed1e7d3d81c9c4d4ec3a740deadc1f).
> 
> Can you confirm the fix? If so, a new release will be tagged soon.

Thanks for the quick reply!

I tried building it from origin/master and got:
'Invalid key: 'use_invidious_api' at /usr/local/share/perl5/5.30/WWW/YoutubeViewer.pm line 179.`
`Undefined subroutine &WWW::YoutubeViewer::set_use_invidious_api called at /usr/bin/youtube-viewer line 1143.`

Should I revert back to [b2ac969](https://github.com/trizen/youtube-viewer/commit/b2ac969756ed1e7d3d81c9c4d4ec3a740deadc1f) and see if that one is OK?

**Comment by trizen** [comment] 2020-05-29 10:01
`/usr/bin/youtube-viewer` seems out-of-date.

Maybe the new version is installed under any of these:

```
/usr/local/bin/youtube-viewer
/usr/bin/site_perl/youtube-viewer
```

**Closed** 2020-05-29 10:21 UTC

**Comment by madalincolea** [comment] 2020-05-29 10:23
Cleaned up the COPR version and reinstalled everything from origin/master.

`-> Resolution: audio`
`-> Video itag: 251`
`-> Video type: audio/webm; codecs="opus"`
`-> Command: /usr/bin/mpv --title=Best\ of\ World\ \#12\ \-\ Songs\ put\ together\ in\ an\ order --no-ytdl --no-video https\:\/\/manifest\.googlevideo\.com\/api\/manifest\/dash\/expire\/1590769141\/ei\/leHQXujeHaO0xN8PlaCTWA\/ip\/86\.125\.41\.121\/id\/26f1a2588ade83e9\/source\/youtube\/requiressl\/yes\/playback_host\/r7\-\-\-sn\-gqn\-vu2l\.googlevideo\.com\/mh\/iT\/mm\/31\%2C29\/mn\/sn\-gqn\-vu2l\%2Csn\-c0q7lnse\/ms\/au\%2Crdu\/mv\/m\/mvi\/6\/pl\/23\/hfr\/all\/as\/fmp4_audio_clear\%2Cwebm_audio_clear\%2Cwebm2_audio_clear\%2Cfmp4_sd_hd_clear\%2Cwebm2_sd_hd_clear\/initcwndbps\/1562500\/vprv\/1\/mt\/1590747407\/fvip\/1\/keepalive\/yes\/fexp\/23882513\/beids\/23886213\/itag\/0\/sparams\/expire\%2Cei\%2Cip\%2Cid\%2Csource\%2Crequiressl\%2Chfr\%2Cas\%2Cvprv\%2Citag\/sig\/AOq0QJ8wRAIgPBsTbs32wBHDbpkJtdwiO6hr\-YYfDz1JJEtW_MW_p34CIB1eK5Po8K6MLVMH4mkwamZfrneK2xfGL\-tsdj0eCPDC\/lsparams\/playback_host\%2Cmh\%2Cmm\%2Cmn\%2Cms\%2Cmv\%2Cmvi\%2Cpl\%2Cinitcwndbps\/lsig\/AG3C_xAwRgIhAPZPT3q\-sfqwu96UE_uxFTx4HUTtFW4fCcE_60gD8pfoAiEAhmzphUZQIVT4msdz4tgQHOkA6n7cZ6SqHAi66Vu2qAI\%3D`
`Failed to recognize file format.`

Tried this with previous commit and the latest you added few minutes ago. Same issue as error above^^

**Comment by trizen** [comment] 2020-05-29 10:25
That seems to be a new error, caused by `mpv`: Failed to recognize file format.

Maybe `mpv` was not compiled with support for `webm`?

Try: `youtube-viewer --prefer-mp4 --id=JvGiWIreg-k`

**Comment by madalincolea** [comment] 2020-05-29 10:26
Hmm, tried that --prefer-mp4 already and still same issue. Will investigate further...

Will keep you posted if I figure out what's what. Thanks for the support so far!
